// Every IPC channel name lives here so the main process and the preload
// script never disagree about spelling. CommonJS so the preload script
// (which runs through Electron's own loader) can require it too.
const CHANNELS = {
  sessionsList: "sessions:list",
  sessionsGet: "sessions:get",
  sessionsChanged: "sessions:changed",
  sessionsRename: "sessions:rename",
  groupsGet: "groups:get",
  groupsCreate: "groups:create",
  groupsRename: "groups:rename",
  groupsMove: "groups:move",
  groupsDelete: "groups:delete",
  groupsAssign: "groups:assign",
  groupsSetHidden: "groups:set-hidden",
  groupsSetCollapsed: "groups:set-collapsed",
  groupsChanged: "groups:changed",
  agentsGet: "agents:get",
  agentsAdd: "agents:add",
  agentsUpdate: "agents:update",
  agentsDelete: "agents:delete",
  agentsInspectFolder: "agents:inspect-folder",
  agentsInspectFile: "agents:inspect-file",
  agentsPickFolder: "agents:pick-folder",
  agentsLinkedSessions: "agents:linked-sessions",
  agentsChanged: "agents:changed",
  systemLanguage: "system:language",
  systemEmojiPanel: "system:emoji-panel",
  projectsRecent: "projects:recent",
  projectsPick: "projects:pick",
  terminalOpen: "terminal:open",
  terminalInput: "terminal:input",
  terminalResize: "terminal:resize",
  terminalList: "terminal:list",
  terminalReplay: "terminal:replay",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",
  terminalChanged: "terminal:changed",
  smokeCommand: "smoke:command",
  panelGet: "panel:get",
  panelOpen: "panel:open",
  panelClose: "panel:close",
  panelActivate: "panel:activate",
  panelSetTitle: "panel:set-title",
  panelSetVisible: "panel:set-visible",
  panelChanged: "panel:changed",
  panelCommand: "panel:command",
  panelSelection: "panel:selection",
  panelReadFile: "panel:read-file",
  panelWatchFile: "panel:watch-file",
  panelUnwatchFile: "panel:unwatch-file",
  panelFileChanged: "panel:file-changed",
  panelOpenExternal: "panel:open-external"
};

module.exports = { CHANNELS };
